name: 🍎 macOS Builds
on:
  workflow_call:
  workflow_dispatch:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.x

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: macos-editor
            target: release_debug
            tools: true
            sconsflags: verbose=yes warnings=all werror=yes debug_symbols=no
            bin: "./bin/godot.osx.opt.tools.64"

          - name: Editor (target=release_debug, tools=yes, debug_symbols=true)
            cache-name: macos-editor-with-debug-symbols
            target: release_debug
            tools: true
            sconsflags: verbose=yes warnings=all werror=yes debug_symbols=yes
            bin: "./bin/godot.osx.opt.tools.with_debug_symbols.64"            


          - name: Template (target=release, tools=no)
            cache-name: macos-template
            target: release
            sconsflags: verbose=yes warnings=all werror=yes debug_symbols=no
            tools: false

    steps:
      - uses: actions/checkout@v4

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ matrix.sconsflags }}
          platform: osx
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          debug_symbols: ${{ matrix.debug_symbols }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
