name: 🔗 GHA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  static-checks:
    name: 📊 Static
    uses: ./.github/workflows/static_checks.yml

  linux-build:
    name: 🐧 Linux
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml
